# JavaBuild.cmake
#
# The following variables must be defined before the INCLUDES()
# declaration in your CMakeLists.txt
#
# SOURCE_FILES: the Java source files to compile
# CLASSPATH: the classpath to use when compiling
# CLASS_OUTPUT_PATH: where to put the compiled classes
# JAR_OUTPUT_PATH: where to put the generated jar file
# JAR_FILE_NAME: the name of the jar file to create
#

FILE(MAKE_DIRECTORY ${CLASS_OUTPUT_PATH})
FILE(MAKE_DIRECTORY ${JAR_OUTPUT_PATH})

IF(NOT WIN32)
  STRING(REGEX REPLACE ";" ":" CLASSPATH_INTERNAL "${CLASSPATH}")
ELSE(NOT WIN32)
  SET(CLASSPATH_INTERNAL ${CLASSPATH})
ENDIF(NOT WIN32)

#write the source list to a file to avoid command line overflow
SET(SOURCE_LIST_FILE ${CMAKE_BINARY_DIR}/${JAR_FILE_NAME}.srclist)
STRING(REGEX REPLACE ";" "\n" SOURCE_FILES_INTERNAL "${SOURCE_FILES}")
FILE(WRITE ${SOURCE_LIST_FILE} ${SOURCE_FILES_INTERNAL})

#Write the resources list to a file so I can remove .svn items
SET(RESOURCE_LIST_FILE ${CMAKE_BINARY_DIR}/${JAR_FILE_NAME}.resourcelist)
STRING(REGEX REPLACE ";" "\n-C ${JAR_RESOURCE_PATH} " RESOURCE_FILES "${RESOURCE_FILES}")
FILE(WRITE ${RESOURCE_LIST_FILE} ${RESOURCE_FILES})

ADD_CUSTOM_TARGET(${JAR_FILE_NAME}-javac ALL ${CMAKE_Java_COMPILER} -classpath "${CLASSPATH_INTERNAL}" -d ${CLASS_OUTPUT_PATH} @${SOURCE_LIST_FILE})

ADD_CUSTOM_TARGET(${JAR_FILE_NAME}-jar ALL ${CMAKE_Java_ARCHIVE} -cf ${JAR_OUTPUT_PATH}/${JAR_FILE_NAME} -C ${CLASS_OUTPUT_PATH} . @${RESOURCE_LIST_FILE})
ADD_DEPENDENCIES(${JAR_FILE_NAME}-jar ${JAR_FILE_NAME}-javac)

IF(DO_SIGN_JARS)
  ADD_CUSTOM_TARGET(${JAR_FILE_NAME}-jarsigner ALL ${Java_JARSIGNER} -keystore ${KEYSTORE_FILE_NAME} -storepass ${KEYSTORE_PASSWORD} -signedJar ${JAR_OUTPUT_PATH}/${SIGNED_JAR_PREFIX}${JAR_FILE_NAME} ${JAR_OUTPUT_PATH}/${JAR_FILE_NAME} ${KEYSTORE_USER_NAME})
  ADD_DEPENDENCIES(${JAR_FILE_NAME}-jarsigner ${JAR_FILE_NAME}-jar)
ENDIF(DO_SIGN_JARS)
