/**
 * EnumerationType3.java
 *
 * This file was generated by XMLSpy 2006r3 Enterprise Edition.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the XMLSpy Documentation for further details.
 * http://www.altova.com/xmlspy
 */


package com.rnaml;

import com.altova.types.*;

public class EnumerationType3 extends SchemaString {
	public static final int E1_0 = 0; /* 1.0 */
	public static final int E1_0B = 1; /* 1.0b */

	public static String[] sEnumValues = {
		"1.0",
		"1.0b",
	};

	public EnumerationType3() {
		super();
	}

	public EnumerationType3(String newValue) {
		super(newValue);
		validate();
	}

	public EnumerationType3(SchemaString newValue) {
		super(newValue);
		validate();
	}

	public static int getEnumerationCount() {
		return sEnumValues.length;
	}

	public static String getEnumerationValue(int index) {
		return sEnumValues[index];
	}

	public static boolean isValidEnumerationValue(String val) {
		for (int i = 0; i < sEnumValues.length; i++) {
			if (val.equals(sEnumValues[i]))
				return true;
		}
		return false;
	}

	public void validate() {

		if (!isValidEnumerationValue(toString()))
			throw new com.altova.xml.XmlException("Value of Enumeration is invalid.");
	}
}
