/**
 * EnumerationType.java
 *
 * This file was generated by XMLSpy 2006r3 Enterprise Edition.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the XMLSpy Documentation for further details.
 * http://www.altova.com/xmlspy
 */


package com.rnaml;

import com.altova.types.*;

public class EnumerationType extends SchemaString {
	public static final int EDNA = 0; /* dna */
	public static final int ERNA = 1; /* rna */

	public static String[] sEnumValues = {
		"dna",
		"rna",
	};

	public EnumerationType() {
		super();
	}

	public EnumerationType(String newValue) {
		super(newValue);
		validate();
	}

	public EnumerationType(SchemaString newValue) {
		super(newValue);
		validate();
	}

	public static int getEnumerationCount() {
		return sEnumValues.length;
	}

	public static String getEnumerationValue(int index) {
		return sEnumValues[index];
	}

	public static boolean isValidEnumerationValue(String val) {
		for (int i = 0; i < sEnumValues.length; i++) {
			if (val.equals(sEnumValues[i]))
				return true;
		}
		return false;
	}

	public void validate() {

		if (!isValidEnumerationValue(toString()))
			throw new com.altova.xml.XmlException("Value of Enumeration is invalid.");
	}
}
