/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_simtk_moleculardynamics_RelaxCoordinates */

#ifndef _Included_org_simtk_moleculardynamics_RelaxCoordinates
#define _Included_org_simtk_moleculardynamics_RelaxCoordinates
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_simtk_moleculardynamics_RelaxCoordinates
 * Method:    relaxCoordinates1
 * Signature: (I[F[FFI[IFFI)I
 */
JNIEXPORT jint JNICALL Java_org_simtk_moleculardynamics_RelaxCoordinates_relaxCoordinates1
  (JNIEnv *, jclass, jint, jfloatArray, jfloatArray, jfloat, jint, jintArray, jfloat, jfloat, jint);

#ifdef __cplusplus
}
#endif
#endif
